FROM nginx:alpine

RUN apk add --no-cache libwebp-tools

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY images/ /data/images/
COPY entrypoint-images.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
