FROM nginx:alpine

RUN apk add --no-cache ffmpeg

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY videos/ /data/videos/
COPY entrypoint-videos.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
